/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: "category",
      label: "CLI",
      items: [
        {
          type: 'autogenerated',
          dirName: 'CLI',
        },
      ],
    },
    {
      type: "category",
      label: "Live",
      items: [
        {
          type: 'autogenerated',
          dirName: 'Live',
        },
      ],
    },
    {
      type: "category",
      label: "Video-on-Demand",
      items: [
        {
          type: 'autogenerated',
          dirName: 'Video-on-Demand',
        },
      ],
    },
    {
      type: "category",
      label: "Javascript Client Integration",
      items: [
        {
          type: 'autogenerated',
          dirName: 'Javascript Client Integration',
        },
      ],
    },
    {
      type: "category",
      label: "Javascript Client Library",
      items: [
        {
          type: 'autogenerated',
          dirName: 'Javascript Client Library',
        },
      ],
    },
    {
      type: "category",
      label: "Contributing",
      items: [
        {
          type: 'autogenerated',
          dirName: 'Contributing',
        },
      ],
    },
    {
      type: 'doc',
      id: 'Troubleshooting',
    },
    {
      type: "category",
      label: "Community site",
      items: [
        {
          type: 'autogenerated',
          dirName: 'community-site',
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
